version: "2.1"
services:
  hub:
    image: selenium/hub:3.9.1
    ports:
      - "4444:4444"

  firefox:
    image: selenium/node-firefox-debug:3.9.1
    ports:
      - "5911:5900"
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    healthcheck:
      test: bash -c "wget -O - http://hub:4444/grid/console 2>&1 | grep \"browserName=firefox\" "
      interval: 10s
      retries: 13

  chrome:
    image: selenium/node-chrome-debug:3.9.1
    ports:
      - "5912:5900"
    environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    healthcheck:
      test: bash -c "wget -O - http://hub:4444/grid/console 2>&1 | grep \"browserName=chrome\" "
      interval: 10s
      retries: 13

  chorus-react-calculator:
    image: node:8.9.1
    ports:
      - "9000:80"
    working_dir: /usr/src/app
    volumes:
      - ../chorus-js-react-calculator:/usr/src/app
    command: bash -c "PORT=80 yarn start"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost && echo 'OK'"]
      interval: 20s
      retries: 15

  chorus-interpreter:
    image: chorus-interpreter:latest
    ports:
      - "9080:9080"
    depends_on:
      - chorus-react-calculator
    volumes:
      - ./features:/features
    command: dockerize -wait tcp://firefox:5900 -wait tcp://chrome:5900 -wait tcp://hub:4444 -wait http://chorus-react-calculator:80 -timeout 30s chorus -f /features



